*** Settings ***
Documentation        Variáveis globais e configurações de ambiente

*** Variables ***
${BASE_URL}           https://compassuolfront.serverest.dev
${USER_PAGE_URL}      https://compassuolfront.serverest.dev/cadastrarusuarios
${FIELD_NAME}         id=nome
${FIELD_EMAIL}        id=email
${FIELD_PASSWORD}     id=password
${BTN_REGISTER}       data-testid=cadastrar
${ALERT_MESSAGE}      css=.alert
